### ISSUE TITLE
Buildings missing in TerraSync

### ISSUE THREAD

**Issue by MIG29pilot** [legoboyvdlp/SVMI-fg-CustomScenery#2]
Hi!
Used the scenery today, noted that the main terminal was missing
![fgfs-screen-020](https://cloud.githubusercontent.com/assets/12913797/11320659/b3708584-906e-11e5-82ff-244353da507a.png)

**Comment by legoboyvdlp** [comment]
Yes, that is because you used TerraSync.
Download this repository, not TerraSync.

**Comment by legoboyvdlp** [comment]
It is impossible to upload it to TerraSync by the way, since there are too many texture files.

**Comment by legoboyvdlp** [comment]
9
